/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.grupojeffmelanienorman;

import org.json.simple.JSONObject;

/**
 * VentanaDetalleMantenimiento
 * 
 * Clase que muestra los detalles de un servicio de mantenimiento.
 *
 * @author Melanie
 */
public class VentanaDetalleMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDetalleFactura
     * @param servicio servicio del cual se quieren ver los detalles
     */
    public VentanaDetalleMantenimiento(JSONObject servicio) {
        jLabel3.setText((String) servicio.get("Codigo Cliente"));
        jLabel5.setText((String) servicio.get("Marca Bicicleta"));
        jLabel7.setText((String) servicio.get("Descripcion Bicicleta"));
        jLabel9.setText((String) servicio.get("Fecha Recibido"));
        jLabel11.setText((String) servicio.get("Fecha Entrega"));
        jLabel13.setText((String) servicio.get("Observaciones"));
        jLabel15.setText((String) servicio.get("Precio"));
        jLabel15.setText((String) servicio.get("Estado"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Detalle Servicio de Mantenimiento Seleccionado");

        jLabel2.setText("Cliente:");

        jLabel3.setText("(cliente)");

        jLabel4.setText("Marca de Bicicleta:");

        jLabel5.setText("(marca)");

        jLabel6.setText("Descripcion de Bicicleta:");

        jLabel7.setText("(descripcion)");

        jLabel8.setText("Fecha Recibido:");

        jLabel9.setText("(fecha)");

        jLabel10.setText("Fecha Entrega:");

        jLabel11.setText("(fecha)");

        jLabel12.setText("Observaciones:");

        jLabel13.setText("(observaciones)");

        jLabel14.setText("Precio:");

        jLabel15.setText("(precio)");

        jLabel16.setText("Estado:");

        jLabel17.setText("(estado)");

        jLabel18.setText("colones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * jLabel1
     */
    private javax.swing.JLabel jLabel1;
    /**
     * jLabel10
     */
    private javax.swing.JLabel jLabel10;
    /**
     * jLabel11
     */
    private javax.swing.JLabel jLabel11;
    /**
     * jLabel12
     */
    private javax.swing.JLabel jLabel12;
    /**
     * jLabel13
     */
    private javax.swing.JLabel jLabel13;
    /**
     * jLabel14
     */
    private javax.swing.JLabel jLabel14;
    /**
     * jLabel15
     */
    private javax.swing.JLabel jLabel15;
    /**
     * jLabel16
     */
    private javax.swing.JLabel jLabel16;
    /**
     * jLabel17
     */
    private javax.swing.JLabel jLabel17;
    /**
     * jLabel18
     */
    private javax.swing.JLabel jLabel18;
    /**
     * jLabel2
     */
    private javax.swing.JLabel jLabel2;
    /**
     * jLabel3
     */
    private javax.swing.JLabel jLabel3;
    /**
     * jLabel4
     */
    private javax.swing.JLabel jLabel4;
    /**
     * jLabel5
     */
    private javax.swing.JLabel jLabel5;
    /**
     * jLabel6
     */
    private javax.swing.JLabel jLabel6;
    /**
     * jLabel7
     */
    private javax.swing.JLabel jLabel7;
    /**
     * jLabel8
     */
    private javax.swing.JLabel jLabel8;
    /**
     * jLabel9
     */
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
